#!/bin/bash

mode=$1

if [ -z "$1" ]
then
	mode="0"
fi
string="\def\printerFriendly{"$mode"}"
echo $string > printermode.tex
xelatex CharacterSheet.tex
#pdfjam CharacterSheet.pdf 2-3	--paper a4paper -o CharacterSheet.pdf
xdg-open CharacterSheet.pdf
