#!/bin/bash
echo $1
if [ $1 -eq  1 ] 
then
	cd Data;
	matlab -nodisplay -nodesktop -r 'MasterAssembly(1)';
	cd ..
fi
xelatex CoreRulebook.tex
#xelatex BasicRulebook.tex
evince CoreRulebook.pdf &
rm *.log

